# Generated by Django 5.0.8 on 2024-10-16 04:52

import django.db.models.deletion
import pbs.review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedburn',
            name='region',
            field=models.PositiveSmallIntegerField(blank=True, choices=pbs.review.models.get_region_choices, null=True),
        ),
    ]
