# Generated by Django 5.2.13 on 2026-05-22 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_layer_alter_aircraftburn_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='layer',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
