# Generated by Django 5.0.13 on 2025-04-29 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='tracks',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='actions',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='aerial_maps',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='edging_plan',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='exclusion_areas',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='fuel_assessment',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='pre_actions',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='roads',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnimplementationstate',
            name='traffic',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
    ]
