# Generated by Django 5.0.13 on 2025-05-02 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_areaachievement_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnclosurestate',
            name='aerial_intensity',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='evaluation',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='other',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='post_actions',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='post_ignitions',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='satellite_intensity',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='burnclosurestate',
            name='signage',
            field=models.BooleanField(blank=True, choices=[(None, 'Not applicable'), (False, 'Incomplete'), (True, 'Complete')], default=False, null=True),
        ),
    ]
