# Generated by Django 3.2.25 on 2024-08-23 01:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescription', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prescription',
            field=models.ForeignKey(help_text='Prescription that this document belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription'),
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.documenttag', verbose_name='Descriptor'),
        ),
    ]
