# Generated by Django 3.2.25 on 2024-08-23 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_initial'),
        ('prescription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='briefingchecklist',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.action'),
        ),
        migrations.AddField(
            model_name='briefingchecklist',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_briefingchecklist_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='briefingchecklist',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_briefingchecklist_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='briefingchecklist',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription'),
        ),
        migrations.AddField(
            model_name='briefingchecklist',
            name='smeac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.smeac', verbose_name='SMEACS'),
        ),
        migrations.AddField(
            model_name='approval',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_approval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_approval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription'),
        ),
        migrations.AlterUniqueTogether(
            name='shire',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='priorityjustification',
            unique_together={('purpose', 'prescription')},
        ),
        migrations.AlterUniqueTogether(
            name='fundingallocation',
            unique_together={('prescription', 'allocation')},
        ),
    ]
