# Generated by Django 5.0.13 on 2025-05-08 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_prescription_archive_successful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='endorsed',
            field=models.BooleanField(blank=True, choices=[(None, ''), (False, 'Reviewed and not endorsed'), (True, 'Endorsed')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='contentious',
            field=models.BooleanField(blank=True, choices=[(None, '-----'), (False, 'No'), (True, 'Yes')], default=None, help_text='Is this burn contentious?', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='non_calm_tenure',
            field=models.BooleanField(blank=True, null=True, verbose_name='Non-CALM Act Tenure'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='non_calm_tenure_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cross Tenure Approved?'),
        ),
    ]
