# Generated by Django 5.2.11 on 2026-04-16 05:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_null_boolean_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='archive_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrescriptionArchiveJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_status', models.CharField(max_length=32)),
                ('previous_status', models.CharField(max_length=64)),
                ('new_status', models.CharField(max_length=64)),
                ('archive_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User whose action triggered this archive job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'requested_at', 'id'],
            },
        ),
    ]
