# Generated by Django 5.2.11 on 2026-04-16 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_alter_approval_initial_valid_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionArchiveJob',
        ),
    ]
