# Generated by Django 3.2.25 on 2024-08-23 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=320)),
                ('organisation', models.TextField()),
                ('person', models.TextField(verbose_name='DPaW Person')),
                ('comments', models.TextField()),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_publiccontact_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_publiccontact_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription')),
            ],
            options={
                'verbose_name': 'Public Contact',
                'verbose_name_plural': 'Public Contacts',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notified', models.DateField(verbose_name='Date of Notification')),
                ('contacted', models.TextField(verbose_name='Person Contacted')),
                ('organisation', models.PositiveSmallIntegerField(choices=[(1, 'Beekeepers'), (2, 'Neighbours'), (3, 'Flora Pickers'), (4, 'Commercial Operators'), (5, 'Radio Stations'), (6, 'Significant Stakeholders'), (7, 'Other')], verbose_name='Organisation Type')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=320)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_notification_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_notification_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriticalStakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=320)),
                ('organisation', models.CharField(max_length=320)),
                ('interest', models.TextField()),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_criticalstakeholder_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_criticalstakeholder_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription')),
            ],
            options={
                'verbose_name': 'Critical Stakeholder',
                'verbose_name_plural': 'Critical Stakeholders',
                'ordering': ['id'],
            },
        ),
    ]
